version: "2"

linters:
  enable:
    - gosec

  exclusions:
    rules:
      # math/rand is intentional in the router — used for Thompson sampling and
      # retry jitter, not for security-sensitive operations (those use crypto/rand).
      - path: internal/router/
        linters: [gosec]
        text: "G404"

      # tokenhubctl explicitly shells out to `docker exec` by design; the
      # container name comes from the user's own config, not untrusted input.
      - path: cmd/tokenhubctl/
        linters: [gosec]
        text: "G204"

      # Health-check URL is constructed from the server's own listen address,
      # not from external input.
      - path: cmd/tokenhub/main\.go
        linters: [gosec]
        text: "G107"

      # File paths in admin_token.go are rooted at os.UserHomeDir() or a
      # server-configured data directory, not at user-supplied input.
      - path: internal/httpapi/admin_token\.go
        linters: [gosec]
        text: "G304"

      # Same for tokenhubctl reading ~/.tokenhub/* files.
      - path: cmd/tokenhubctl/main\.go
        linters: [gosec]
        text: "G304"

      # Credentials file path comes from os.UserHomeDir() in server.go.
      - path: internal/app/server\.go
        linters: [gosec]
        text: "G304"

      # credProvider is a local (unexported) struct used only to deserialize a
      # credentials config file; it does not expose the key value externally.
      - path: internal/app/server\.go
        linters: [gosec]
        text: "G117"

      # slog's structured key=value format prevents log-injection newline attacks;
      # IP and path are logged only for audit visibility, not user-facing output.
      - path: internal/apikey/middleware\.go
        linters: [gosec]
        text: "G706"

      # TOKENHUB_URL is an operator-set env var (defaulting to localhost); there
      # is no external attacker input involved in constructing the request URL.
      - path: cmd/tokenhubctl/main\.go
        linters: [gosec]
        text: "G704"

      # Output is written to os.Stderr in a CLI tool — XSS does not apply to
      # terminal output; there is no HTTP response context here.
      - path: cmd/tokenhubctl/main\.go
        linters: [gosec]
        text: "G705"

      # Test files are not production attack surface.
      - path: _test\.go
        linters: [gosec]
